language: node_js
node_js:
  - "16.13.2"
services:
  - xvfb
dist: trusty
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gui --remote-debugging-port=9222 http://localhost &
script:
  - xvfb-run npm test